### ISSUE TITLE
圖片畫質在preview時很好，上傳交誼廳會變差

### ISSUE THREAD

**Issue by ghost** [watchout-tw/discourse#1]
_From @aging29 on August 18, 2015 9:53_

圖片上傳到交誼廳後在文章裡顯示時，以mac air & pro為例，圖片邊緣會有毛邊情形，螢幕亮度較亮時會比較明顯。

_Copied from original issue: watchout-tw/blog.citizenedu.tw#7_

**Comment by wayne930242** [comment]
http://community.citizenedu.tw/t/topic/1524/6?u=weihung

看起來沒問題。
