### ISSUE TITLE
交誼聽編碼顯示有誤

### ISSUE THREAD

**Issue by ghost** [watchout-tw/discourse#10]
_From @aging29 on January 5, 2016 2:8_

<img width="737" alt="2016-01-05 10 06 23" src="https://cloud.githubusercontent.com/assets/8164369/12105883/35380b3a-b394-11e5-87f4-dd1c17cb1660.png">

_Copied from original issue: watchout-tw/blog.citizenedu.tw#51_

**Comment by wesley100002001** [comment]
已經交誼廳更新到 discourse 1.5.2 版 (stable)
此問題隨著更新已解決。
