### ISSUE TITLE
20160418 交誼廳註冊問題

### ISSUE THREAD

**Issue by kc5** [watchout-tw/discourse#12]
1. 公民學院交誼廳註冊時要輸入電郵地址，接著會寄確認信
2. 但是過了15分鐘都沒有收到

註：PM測試情況的錯誤截圖回報：https://watchouttw.hackpad.com/-20160418--9cc3eGy3848
註：公民學院交誼廳網址：http://community.citizenedu.tw/

**Comment by wesley100002001** [comment]
所以收到信了嗎？

**Comment by kc5** [comment]
Hi, 家偉
我剛才重新確認後，加上了一些註解，寫在PAD裡
再麻煩家偉幫忙看看
https://watchouttw.hackpad.com/-20160418--9cc3eGy3848
