### ISSUE TITLE
[最新] 20160624 烙哲學更新網址後依然無法登入

### ISSUE THREAD

**Issue by kc5** [watchout-tw/discourse#16]
目前透過citizenedu.tw的網址無法登入，仍須透過community.citizenedu.tw 此網站連上交誼廳才有辦法登入。

**Comment by wesley100002001** [comment]
是用 Facebook / Google 帳號登入嗎？還是直接輸入帳號密碼登入？
我用 Facebook / Google 帳號都可以正常登入。

**Comment by kc5** [comment]
上周末與UDN的窗口聯繫時對方表示無法登入，是直接重新用Google註冊才可以，不過現在好像好了！？ＸＤ　目前測試或是重新註冊也是都可以。我close這個issue好囉～

**Comment by wesley100002001** [comment]
感謝～
