### ISSUE TITLE
無法用 facebook 和 twitter 帳號註冊

### ISSUE THREAD

**Issue by wayne930242** [watchout-tw/discourse#18]
如題，有人回報。 google 帳號沒有試過，不知道是否可以。

**Comment by wesley100002001** [comment]
需要更多的訊息，想問一下 User 用的是什麼瀏覽器？無法註冊的時候是出現什麼畫面呢？

**Comment by wesley100002001** [comment]
Twitter 早上新增之後測試完確定可以

**Comment by wesley100002001** [comment]
重啟 discourse 之後，Facebook 復原，再麻煩 @wayne930242 幫我測試一下。

**Comment by wesley100002001** [comment]
目前已無此問題
