### ISSUE TITLE
bubble 的 bug

### ISSUE THREAD

**Issue by wayne930242** [watchout-tw/discourse#19]
我將「烙哲學專欄」頻道刪掉之後就無法再新增同一個頻道。

**Comment by wesley100002001** [comment]
的確有此問題，我已在 bubble 的 Github repo 提出這個 issue

**Comment by wesley100002001** [comment]
官方公告，將會在下一個版本解決。
https://github.com/gdpelican/babble/issues/216

**Comment by wesley100002001** [comment]
已決定不使用 Babble，issue close。
