### ISSUE TITLE
客製化摘要的功能

### ISSUE THREAD

**Issue by ghost** [watchout-tw/discourse#8]
_From @pm5 on September 8, 2015 7:59_

有些文章比較合適的摘要其實在最後幾段，或是編輯要自己寫。希望提供客製化摘要的功能，但格式還沒想好。

_Copied from original issue: watchout-tw/blog.citizenedu.tw#25_

**Comment by ghost** [comment]
_From @aging29 on September 29, 2015 11:27_

客製化摘要是不是可以跟編輯導讀合併？

**Comment by ghost** [comment]
_From @pm5 on September 30, 2015 9:1_

那就放編輯導讀試試看。等 #26 做好來放。

**Comment by wayne930242** [comment]
需求修改。
