### ISSUE TITLE
[1] 註冊交誼廳email 錯誤訊息

### ISSUE THREAD

**Issue by ghost** [watchout-tw/discourse#9]
_From 阿金 on December 23, 2015 9:29_

目前交誼廳註冊新帳號時，會出現email相關的錯訊息

![screen shot 2015-12-23 at 4 42 03 pm](https://cloud.githubusercontent.com/assets/8164369/11973973/9f2b4060-a99a-11e5-9c23-d90ab0b03825.png)

_Copied from original issue: watchout-tw/blog.citizenedu.tw#50_

**Comment by kc5** [comment]
公民學院交誼廳註冊時要輸入電郵地址，接著會寄確認信
但是過了15分鐘都沒有收到
註：PM測試情況的錯誤截圖回報：https://watchouttw.hackpad.com/-20160418--9cc3eGy3848
註：公民學院交誼廳網址：http://community.citizenedu.tw/

**Comment by wayne930242** [comment]
![default](https://cloud.githubusercontent.com/assets/5166321/15135522/b54b5f84-16a9-11e6-8c90-8373c4cd5511.PNG)

可以看到，自從 2015 年 9 月以後，mailgun 就沒有成功運作了。

**Comment by wesley100002001** [comment]
實際設定 server 之後發現，當初並沒有使用 mailgun，而是使用了 mandrill 的 Email 服務。而昨天發現 mandrill 被 MailChimp 合併了，而我們並沒有在指定的時間內完成轉移，所以 mandrill 目前已經無法使用。昨天重新註冊了 mailgun，等待 48 小時之後再看看是否回覆正常。

**Comment by wesley100002001** [comment]
原來過了 48 小時之後需要再啟用才能正常使用，早上啟用了 Mailgun 並用交誼廳寄送了測試信件，目前正常，再麻煩 @kc5 測試一下～

**Comment by wesley100002001** [comment]
問題已解決
